---
title: "Dashboard by Caro"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(tidyverse)
library(plotly)
library(dplyr)
library(tidyr)

nyc_restaurant_inspections =
   rest_inspec |>
   drop_na(grade)|>
   select(boro, critical_flag,cuisine_description, inspection_date, grade)|>
   separate(inspection_date, into = c("year" , "month", "day"), sep = "-")|>
     filter(grade %in% c("A", "B", "C"), boro != "Missing") 
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A: Health Department Inspection Grades by Borough 

```{r}
plot1=
   nyc_restaurant_inspections |>
  filter(grade %in% c("A", "B", "C"), boro != "Missing") |>    
  mutate(boro = fct_infreq(boro)) |> 
  count(boro, grade) |> 
  plot_ly(x = ~boro, y = ~n, color = ~grade, type = 'bar', colors = "Set1") |> 
  layout(title = "Count of Restaurant Grades by Borough",
         xaxis = list(title = "Borough"),
         yaxis = list(title = "Count"),
         barmode = 'stack')

ggplotly(plot1)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B: Counts of Critical Flags by Borough 

```{r}
plot2=
   nyc_restaurant_inspections |>
  filter(grade %in% c("A", "B", "C"), 
         boro != "Missing", 
         critical_flag != "Not Applicable") |>    
  mutate(boro = fct_infreq(boro)) |>
  group_by(boro, critical_flag) |>
  summarize(n = n(), .groups = 'drop') |> 
  plot_ly(x = ~boro, y = ~n, color = ~critical_flag, type = 'bar', 
          colors = "Set1", 
          text = ~paste("Count:", n),
          hoverinfo = 'text') |> 
  layout(title = "Counts of Critical Flags by Borough",
         xaxis = list(title = "Borough"),
         yaxis = list(title = "Count"),
         barmode = 'dodge',  # Set bar mode to dodge
         legend = list(title = list(text = "Critical Flag")))

ggplotly(plot2)
```

### Chart C: Plot 3: Health Department Critical Flags by Grades & Borough

```{r}
plot3=
   nyc_restaurant_inspections |>
  filter(boro != "Missing", cuisine_description != "Missing") |>    
  mutate(boro = fct_infreq(boro)) |>
  group_by(boro, grade, critical_flag) |>
  summarize(n = n(), .groups = 'drop') |> 
  ggplot(aes(x = n, y = grade, fill = critical_flag)) +  
  geom_bar(stat = "identity", position = "dodge") +  
  labs(title = "Count of Grades by Borough and Critical Flag", 
       x = "Count", 
       y = "Grade") +
  theme_minimal() +
  facet_grid(~ boro) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplotly(plot3)

```


