---
title: "Dashboard by Caro"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(tidyverse)
library(plotly)
library(dplyr)
library(tidyr)

nyc_restaurant_inspections =
   rest_inspec |>
   drop_na(grade)|>
   select(boro, critical_flag,cuisine_description, inspection_date, grade)|>
   separate(inspection_date, into = c("year" , "month", "day"), sep = "-")|>
     filter(grade %in% c("A", "B", "C"), boro != "Missing") 
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A: Health Department Inspection Grades by Borough 

```{r}
nyc_restaurant_inspections|>
  filter(grade %in% c("A", "B", "C"), boro != "Missing") |>    
  mutate(
    boro = fct_infreq(boro))|>
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar()
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B: Counts of Critical Flags by Borough 

```{r}
nyc_restaurant_inspections|>
  filter(grade %in% c("A", "B", "C"), boro != "Missing", critical_flag != "Not Applicable") |>    
  mutate(
    boro = fct_infreq(boro))|>
   group_by(boro, critical_flag, cuisine_description)|>
   summarize(n=n())|>
  ggplot(aes(x = boro)) + 
  geom_bar(aes(y = n, fill = critical_flag), stat = "identity", position = "dodge") + 
  labs(title = "Counts of Critical Flags by Borough",
       x = "Borough",
       y = "Count",
       fill = "Critical Flag") +
  theme_minimal()
```

### Chart C: Plot 3: Health Department Critical Flags by Grades & Borough

```{r}
plot3=
   nyc_restaurant_inspections |>
  filter(boro != "Missing", cuisine_description != "Missing") |>    
  mutate(boro = fct_infreq(boro)) |>
  group_by(boro, grade, critical_flag) |>
  summarize(n = n(), .groups = 'drop') |> 
  ggplot(aes(x = n, y = grade, fill = critical_flag)) +  
  geom_bar(stat = "identity", position = "dodge") +  
  labs(title = "Count of Grades by Borough and Critical Flag", 
       x = "Count", 
       y = "Grade") +
  theme_minimal() +
  facet_grid(~ boro) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplotly(plot3)
```


